### ISSUE TITLE
Create Material 3 Progress Ring

### ISSUE THREAD

**Issue by CollinHerber** [Betsy-Bot/betsy-web-components#5]
The current loading indicator is Material 2 and needs update

**Comment by Eleidyssb** [comment]
Which load indicator are we referring to, any of these?



![Image](https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/bb07b4cd-fb71-4d57-9daf-ab2ed946f02c)



![Image](https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/a67cdda8-f41f-42c0-97ca-b9f13787083c)



![Image](https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/bc7f1919-e863-452e-b93c-2867ac5788cd)


Is it possible to show only a loading icon? Right now the one that fetching data and the one from devextreme are shown, but both have different colors. 


https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/6e80e9ec-53e4-4858-a674-56576efbe43b

**Comment by CollinHerber** [comment]
This update was released in 2.4.0 so your screenshots would not have had the new progress indicator. This one is rather hard to test because they go away so fast

**Comment by Eleidyssb** [comment]
I'm not sure if this ticket was referring to these progress rings, but they are now consistent in color



![Image](https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/75d8381c-2d89-4118-ab1b-adbfe1773bbf)



![Image](https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/1eb6e460-010c-416d-9b83-aeec4a778471)



![Image](https://github.com/Betsy-Bot/betsy-web-components/assets/82000956/42867214-c2da-4cff-9376-f01b82acb028)
